language: python

python:
  - "3.7"
  - "3.8"
  - "3.9"

env:
  - DJANGO=django==2.2.20
  - DJANGO=django==3.1.8
  - DJANGO=django==3.2
  - DJANGO=django==4.0
  - DJANGO=django==4.1

matrix:
  exclude:
    # Django doesn't support following combinations
    - python: 3.7
      env: DJANGO=django==4.0


# command to install dependencies
install:
  - pip install -e .
  - pip install $DJANGO
  - pip install codecov

script:
  - coverage run --include=../* runtests.py

after_success:
  - codecov
